### ISSUE TITLE
Time to string test fails

### ISSUE THREAD

**Issue by viraptor** [OpenKMIP/PyKMIP#124]
I'm not sure I understand how far this issue goes, but the date_time test_str test fails in some locations.

```
_StringException: Traceback (most recent call last):
  File "/home/viraptor/Projects/PyKMIP/kmip/tests/unit/core/primitives/test_date_time.py", line 97, in test_str
    self.assertEqual(s, str(date_time))
  File "/home/viraptor/Projects/PyKMIP/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py", line 362, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/viraptor/Projects/PyKMIP/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py", line 447, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: 'Tue Aug 11 09:18:55 2015' != 'Tue Aug 11 08:18:55 2015'
```

Due to different dates the summer time is active, it looks like the test will fail in some locations (Australia, VIC) but not others. I'm not sure what the solution is here, but I think this code shouldn't try to use/interpret local times at all.

For comparison: Australia/VIC:
```
>>> datetime.datetime.fromtimestamp(time.mktime((2015, 8, 11, 9, 18, 55, 1, 223, 1)))
datetime.datetime(2015, 8, 11, 8, 18, 55)
>>> datetime.datetime.fromtimestamp(time.mktime((2015, 8, 11, 9, 18, 55, 1, 223, 0)))
datetime.datetime(2015, 8, 11, 9, 18, 55)
```
UTC:
```
>>> datetime.datetime.fromtimestamp(time.mktime((2015, 8, 11, 9, 18, 55, 1, 223, 1)))
datetime.datetime(2015, 8, 11, 9, 18, 55)
>>> datetime.datetime.fromtimestamp(time.mktime((2015, 8, 11, 9, 18, 55, 1, 223, 0)))
datetime.datetime(2015, 8, 11, 9, 18, 55)
```

**Comment by PeterHamilton** [comment]
Interesting. I'll take a look at this and see if I can learn more about what's happening. A minor bug fix might be in order.

**Comment by PeterHamilton** [comment]
Ok, this is a bug that should be easy to fix. Instead of hard coding the expected string value:
`s = "Tue Aug 11 09:18:55 2015"`
we should dynamically generate it using the same calls used by the test and the `DateTime` object:
`s = time.ctime(int(time.mktime(t)))`
That will ensure that the expected value always matches the current locale.

I'll post a quick fix for this in a minute. It also looks like this only affects `0.4.1` since the impacted code was added with that release.
