### ISSUE TITLE
statement about "auth_suite" is not  accurate

### ISSUE THREAD

**Issue by vbnmmnbv** [OpenKMIP/PyKMIP#264]
"
Note: TLS1.2 can only be used with versions of Python that support TLS 1.2 (e.g,. Python 2.7.9+ or Python 3.4+). If you are running on an older version of Python, you will only be able to use basic TLS 1.0 authentication.
"
probably is not very accurate.

I did some investigation. For example, package "ssl" in python 2.7.6 doesn't have the constant "PROTOCOL_TLSv1_2" defined. But actually "ssl" is just a very thin wrapper of openssl.  PROTOCOL_TLSv1_2 is 5 in openssl. As long as we pass 5 to it, it should work.

So probably we can come up with some workarounds instead of saying "only be able to use basic TLS 1.0 authentication"?

**Comment by PeterHamilton** [comment]
This may be true. I've never tried to work around Python ssl to invoke features in the underlying openssl backend. However, I would **never** advocate for this approach. The use of unsupported or undocumented security features is a danger zone and I do not want to encourage PyKMIP users to enter it.

If a user is able to install or update openssl to support TLS1.2, that user should also be able to update Python to 2.7.9+ or 3.4+. Python 2.7.9 was released in December 2014 and Python 3.4 was released in March 2014. If a user is tied to an old version of Python due to backwards compatibility issues, then that user needs to make a tradeoff decision between supporting old features and better security.

**Comment by vbnmmnbv** [comment]
Fair enough. As KMIP server is there mainly for the KMIP protocol testing, it shouldn't be a big deal as long as client supports TLS1.2 (by using PROTOCOL_SSLv23).
