### ISSUE TITLE
Is there any config can set username/password info which used by server

### ISSUE THREAD

**Issue by xcgj** [OpenKMIP/PyKMIP#602]
I have read the issue of "How do I configure the username and password credentials on the server?", and see objects.py have added UsernamePasswordCredential code. But when I read the server.py or session.py or engine.py, I didn't see the use of username/password. Did I miss some important code? 
I just want the server to verify the username/password when establish a session, but I don't know how to config

**Comment by PeterHamilton** [comment]
Hi @xcgj, thanks for filing this issue. You haven't missed anything; the server does not currently support enforcing username/password credentials. All user/client authentication is done with the client certificate. The `UsernamePasswordCredential` was added so that the client can support username/password authentication with other KMIP servers.

**Comment by xcgj** [comment]
Got it. Thank you for answer.

**Comment by PeterHamilton** [comment]
No problem. Let me know if you have any other questions. For now, I'll close this issue.
