### ISSUE TITLE
Certificate validation failed with "doesn't contain any IP SANs" (help wanted)

### ISSUE THREAD

**Issue by mshamn6x** [OpenKMIP/PyKMIP#647]
Hi Peter, 

I tired creating KMIP client in go. Initially created  TLS connection as follows, 

```
	tlsConfig := tls.Config{
		CipherSuites: []uint16{ tls.TLS_RSA_WITH_AES_128_CBC_SHA256},
		PreferServerCipherSuites: true,
		RootCAs:      pool,
		Certificates: []tls.Certificate{clientCert},
		MinVersion:   tls.VersionTLS12,
		InsecureSkipVerify: true,
	}
```

with **_InsecureSkipVerify: true_**, then able to perform all KMIP operation without any issues, when changing this field to "False" faced following issue, 

  ```
x509: cannot validate certificate for <IP> because it doesn't contain any IP SANs
  panic: failed to connect: x509: cannot validate certificate for <IP> because it doesn't contain any IP SANs
```

Later understood that is this set to true then we need to add "ServerName" field with hostname's IP or name. If this is configured , then in certificate we need to add property SANs , hence added the same using following code in _bin/create_certificates.py_ 

```
          _add_extension(
          x509.SubjectAlternativeName([
            # Describe what sites we want this certificate for.
            x509.DNSName(u"kmip.com"),
            x509.DNSName(u"www.kmip.com"),
            x509.DNSName(u"py.kmip.com"),
          ]),
          critical=False
          )_
```

Once certificates created with above property, observed following, 

![image](https://user-images.githubusercontent.com/66402782/118994949-5febdc00-b9a4-11eb-9a78-724f6febcacf.png)

After this changing TLS configuration 

```
	tlsConfig := tls.Config{
                ServerName:   "kmip.com",
		CipherSuites: []uint16{ tls.TLS_RSA_WITH_AES_128_CBC_SHA256},
		PreferServerCipherSuites: true,
		RootCAs:      pool,
		Certificates: []tls.Certificate{clientCert},
		MinVersion:   tls.VersionTLS12,
		InsecureSkipVerify: false,
	}
```

With this above modification I able to perform all KMIP operation connection established and above mentioned error not observed.

1. Whether this approach of changing certificate and TLS configuration is correct ? or is there any other way to perform this TLS connection though we configure **_InsecureSkipVerify: false,_**?

2. In LibKMIP do we have any similar functionalities i.e. _InsecureSkipVerify: true, false_ settings ? As of now certificates are generated without SANs property and that means by default InsecureSkipVerify is true hence hostname validation will be skipped ?

Kindly leave a reply.

**Comment by PeterHamilton** [comment]
Hi @mshamn6x, thanks for filing this issue. I'm not as familiar with TLS support in Go as I am with Python, so the TLS Go documentation should be your guide here. That said, I would never recommend setting `InsecureSkipVerify` to `true` (outside of a development or testing environment) as that severely undermines the security of your TLS connection. I have not seen that `x509` IP SANs error before, though if your certificate does not have a `CommonName` defined than I could see the lack of a SAN causing errors. I'd double check whether or not the TLS certificate works if you use a `CommonName` instead of a SAN.

`libkmip` is primarily focused on building and parsing KMIP messages, but it does also include an OpenSSL BIO layer that can be used to build client applications that connect via TLS to a KMIP server. Any configuration of the OpenSSL BIO object (which controls the TLS settings) is done outside of `libkmip` proper, so you have full control over that. You can even choose to skip using the BIO altogether and send the KMIP messages to your KMIP server via other channels, if you really want to.

**Comment by mshamn6x** [comment]
Hi @PeterHamilton Thankyou for your response. I'll looked into documentation regarding GO TLS kind of fixed it but observing some other issues. Those all are common TLS related. I'll keep on work on that. Thanks for your help. This issue can be closed.

**Comment by PeterHamilton** [comment]
@mshamn6x No problem, glad you're making progress! I'll close this issue for now, but feel free to comment again if you have further questions.
