### ISSUE TITLE
Key name should not have space in it

### ISSUE THREAD

**Issue by wew036** [OpenKMIP/PyKMIP#78]
SafeNet is a popular KMIP server.  However, it does not allow any spaces in the name of the key.  Therefore, the create script should not use "Test Key" as name in order to support SafeNet.  The patch below works on SafeNet 8.1.0:

diff --git a/kmip/demos/units/create.py b/kmip/demos/units/create.py
index 8a08cc1..22d6f95 100644
--- a/kmip/demos/units/create.py
+++ b/kmip/demos/units/create.py
@@ -107,7 +107,7 @@ if **name** == '**main**':
     length_obj = attribute_factory.create_attribute(attribute_type,
                                                     length)
     name = Attribute.AttributeName('Name')
-    name_value = Name.NameValue('Test Key')
-    name_value = Name.NameValue('TestKey')
   name_type = Name.NameType(NameType.UNINTERPRETED_TEXT_STRING)
   value = Name(name_value=name_value, name_type=name_type)
   name = Attribute(attribute_name=name, attribute_value=value)

**Comment by PeterHamilton** [comment]
This is a good point. However, I'd rather handle this by adding the name parameter to the argument parser, rather than hard coding a new name value. This is how the name is handled for other demo scripts, like for the `create_key_pair` and `locate` operations. See the `build_cli_parser` function in `kmip/demos/utils.py` for where this is done.

Also, if you'd like to submit code fixing this, feel free to create a pull request. I try to review and respond to new patches as fast as I can.
